doctor/urls.py
from django.conf.urls import url
from doctor.paymen_views import DoctorRegisterPayment, SponsorPayment, UserMeetPayment
from doctor.views import BaseIndexView, DashboardView, Test, DoctorFormsView, \
    DoctorBlogDetailView, DoctorTvView, SendMail, DoctorBaseSearchView, \
    ChangeProfilePicture,  MeetDoctorTestView, DashboradEducation, \
    DashboradWork, DashboradNealiyyet, ChangeProfilePictureOne, ChangeProfilePictureTwo, \
    DashboardMeetDateView, DoctorRegisterPaymentSuccess, DoctorDetailTestView, \
    SposorMoneyView, DoctorAddBlog, DoctorBlogList, MeetingDoneView, PasiendListView, \
    AddReview
from .views import doctor_comment_ajax

urlpatterns = [
    url(r'^$', BaseIndexView.as_view(), name="index"),
    url(r'^dashboard/$', DashboardView.as_view(), name="dashboard"),
    # url(r'^', include("news.urls")),
    # base settings page
    url(r'^dashboard/education/$', DashboradEducation.as_view(), name="dashboard-education"),
    url(r'^dashboard/work_experience/$', DashboradWork.as_view(), name="dashboard-work"),
    url(r'^dashboard/activities/$', DashboradNealiyyet.as_view(), name="dashboard-activity"),
    url(r'^dashboard/personal-info/$', DashboardView.as_view(), name="dashboard-personal"),
    url(r'^dashboard/meet-date/$', DashboardMeetDateView.as_view(), name="dashboard-meet-date"),
    url(r'^dashboard/payment/$', DoctorRegisterPaymentSuccess.as_view(), name="dashboard-payment-success"),
    url(r'^dashboard/sponsored/$', SposorMoneyView.as_view(), name="dashboard-sponsor"),
    url(r'^dashboard/pasients/$', PasiendListView.as_view(), name="dashboard-pasient"),
    url(r'^dashboard/add_review/$', AddReview.as_view(), name="add-review"),

    url(r'^testing/$', Test.as_view(), name="test"),
    url(r'^forms/$', DoctorFormsView.as_view(), name="doctor-blog"),
    url(r'^ajax/comment-ajax/(?P<id>[-\w]+)/dsdsds/$', doctor_comment_ajax, name="doctor_comment_ajax"),
    url(r'^tv/$', DoctorTvView.as_view(), name="doctor-tv"),
    url(r'^blog/(?P<slug>[-\w]+)/$', DoctorBlogDetailView.as_view(), name="doctor-blog"),
    url(r'^sendmail/$', SendMail.as_view(), name="send-mail"),
    url(r'^search/$', DoctorBaseSearchView.as_view(), name="search"),
    url(r'^doctor/(?P<slug>[-\w]+)/$', DoctorDetailTestView.as_view(), name="doctor-detail"),
    url(r'^doctor/add/blog/$', DoctorAddBlog.as_view(), name="doctor-add-blog"),
    url(r'^doctor/list/blog/$', DoctorBlogList.as_view(), name="doctor-blog-list"),
    url(r'^meet/doctor/$', MeetDoctorTestView.as_view(), name="doctor-meet"),
    url(r'^meet/done/$', MeetingDoneView.as_view(), name="doctor-meeting-done"),
    url(r'^picture/upload/$', ChangeProfilePicture.as_view(), name="upload-picture"),
    url(r'^picture/upload/one/$', ChangeProfilePictureOne.as_view(), name="upload-picture1"),
    url(r'^picture/upload/two/$', ChangeProfilePictureTwo.as_view(), name="upload-picture2"),


    # Odenishlerin url tehlukesiz
    url(r'^user/meeting/payment/$', UserMeetPayment.as_view(), name="pay-user-meet"),
    url(r'^doctor/registration/payment/$', DoctorRegisterPayment.as_view(), name="pay-doctor-register"),
    url(r'^doctor/sponsored/payment/$', SponsorPayment.as_view(), name="pay-doctor-sponsored"),

]

tezsagal_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils import translation
from django.views import generic
from doctor.paymen_views import BasePaymentCheckView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^payments/', BasePaymentCheckView.as_view(), name='payment-check'),
    url(r'^e8b138ed91cf.html$', generic.TemplateView.as_view(template_name='e8b138ed91cf.html'), name='site-verification-com'),
    url(r'^e6e7c523116a.html$', generic.TemplateView.as_view(template_name='e6e7c523116a.html'), name='site-verification-az'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

translation.activate(settings.LANGUAGE_CODE)

urlpatterns += i18n_patterns(
    url(r'^', include("doctor.urls", namespace="base")),
    url(r'^pages/', include('django.contrib.flatpages.urls'), name='flat'),
    url(r'^account/', include("base_user.urls", namespace="account")),
)

doctor/forms.py
from django import forms
from doctor.models import ContactMessages, DoctorBlog
from PIL import Image
from geoposition.forms import GeopositionField

VALID_IMAGE_FILETYPES = (
    '.jpg','.png','.tiff'
)

class LeaveMessageForm(forms.ModelForm):
    class Meta:
        model = ContactMessages
        fields = ('name', 'phone', 'message')


class DashboardPersonalForm(forms.Form):
    base_name = forms.CharField(max_length=255)
    personal_info = forms.Textarea()

class BlogAddForm(forms.ModelForm):
    class Meta:
        model = DoctorBlog
        fields = ('author','title', 'image', 'text')

    def __init__(self, *args, **kwargs):
        super(BlogAddForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].required = True


class PositionForm(forms.Form):
    position = GeopositionField()
class ChangePictureForm(forms.Form):

    profile_image = forms.FileField()
    # Add some custom validation to image field
    def clean_photo(self):
        photo = self.cleaned_data.get(['profile_picture'])
        if photo:
            format = Image.open(photo.file).format
            photo.file.seek(0)
            if format in VALID_IMAGE_FILETYPES:
                return photo
        raise forms.ValidationError('Yalnız jpg, png və tiff formatında şəkillər qəbul olunur')

doctor/views.py
from decimal import Decimal

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView, FormView, DetailView, ListView
from django.http import JsonResponse, HttpResponse, Http404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template, render_to_string
from django.conf import settings
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext as _
from geoposition import Geoposition

from doctor.models import BaseContact, ContactMessages, BaseSlider, DoctorBlog, BlogTv, \
    Xestelik, Country, Doctor, DoctorXestelik, DoctorCountry, DoctorTimeTable, \
    SponsorModel, MeetingModels, BlogComment, Banner
from doctor.forms import LeaveMessageForm, ChangePictureForm, \
    DashboardPersonalForm, BlogAddForm, PositionForm
from doctor.options.decorators import LoginRestrictedMixin
from doctor.tasks import MeetingRequestToDoctor, ReviewMessages

from datetime import datetime
from threading import Thread

User = get_user_model()


# Create your views here.
class TezsagalBaseView(View):
    def get_nav_menu_contacts(self):
        obj = BaseContact.objects.all().last()
        return obj

    def get_context_data(self, **kwargs):
        context = super(TezsagalBaseView, self).get_context_data(**kwargs)
        context['base_menu_contact'] = self.get_nav_menu_contacts()
        return context


class BaseIndexView(TezsagalBaseView, TemplateView):
    template_name = 'production/main_index/home.html'

    def get_slider(self):
        obj = BaseSlider.objects.filter(status=True)
        return obj

    def get_context_data(self, **kwargs):
        context = super(BaseIndexView, self).get_context_data(**kwargs)
        context['slider'] = self.get_slider()
        context['ill'] = Xestelik.objects.all()
        context['country'] = Country.objects.all()
        return context


class DashboardView(LoginRestrictedMixin,
                    TezsagalBaseView,
                    TemplateView):
    template_name = 'production/dashboard/dashboard_base.html'
    my_form = DashboardPersonalForm
    success_url = ''

    def post(self, request, *args, **kwargs):
        doctors = Doctor.objects.get(user=request.user)
        xestelikler = request.POST.getlist('ilness')
        sheherler = request.POST.getlist('area')
        if xestelikler:
            for id in xestelikler:
                try:
                    DoctorXestelik.objects.get(xestelik_id=id, doctor=doctors)
                    pass
                except:
                    xes = DoctorXestelik(
                        xestelik_id=id,
                        doctor=doctors
                    )
                    xes.save()
        if sheherler:
            for y in sheherler:
                try:
                    DoctorCountry.objects.get(country_id=y, doctor=doctors)
                    pass
                except:
                    sheh = DoctorCountry(
                        country_id=y,
                        doctor=doctors
                    )
                    sheh.save()
        if not doctors.step_1:
            doctors.phone = request.POST.get('phone', '')
            doctors.prize_type = request.POST.get('prize_type', '')
            doctors.facebook_link = request.POST.get('facebook_link', '')
            doctors.twitter_link = request.POST.get('twitter_link', '')
            doctors.instagram_link = request.POST.get('instagram_link', '')
            doctors.base_name = request.POST.get('base_name', '')
            doctors.language = request.POST.get('language', '')
            doctors.qebul_qiymeti = request.POST.get('qebul_qiymeti', 0)
            doctors.pasient_types_az = request.POST.get('pasient_types_az', '')
            doctors.pasient_types_ru = request.POST.get('pasient_types_ru', '')
            doctors.pasient_types_ka = request.POST.get('pasient_types_ka', '')
            doctors.description_az = request.POST.get('personal_info_az', '')
            doctors.description_ru = request.POST.get('personal_info_ru', '')
            doctors.description_ka = request.POST.get('personal_info_ka', '')
            position_lat = request.POST.get('position_0')
            position_lon = request.POST.get('position_1')
            if position_lat:
                latitude = position_lat
            else:
                latitude = 0
            if position_lon:
                longitude = position_lon
            else:
                longitude = 0
            doctors.position = Geoposition(latitude, longitude)
            doctors.step_1 = True
            doctors.save()
            return redirect(reverse('base:dashboard-education'))
        else:
            doctors.phone = request.POST.get('phone', '')
            doctors.facebook_link = request.POST.get('facebook_link', '')
            doctors.prize_type = request.POST.get('prize_type', '')
            doctors.twitter_link = request.POST.get('twitter_link', '')
            doctors.instagram_link = request.POST.get('instagram_link', '')
            doctors.base_name = request.POST.get('base_name', '')
            doctors.language = request.POST.get('language', '')
            doctors.qebul_qiymeti = request.POST.get('qebul_qiymeti', 0)
            doctors.pasient_types_az = request.POST.get('pasient_types_az', '')
            doctors.pasient_types_ru = request.POST.get('pasient_types_ru', '')
            doctors.pasient_types_ka = request.POST.get('pasient_types_ka', '')
            doctors.description_az = request.POST.get('personal_info_az', '')
            doctors.description_ru = request.POST.get('personal_info_ru', '')
            doctors.description_ka = request.POST.get('personal_info_ka', '')
            position_lat = request.POST.get('position_0')
            position_lon = request.POST.get('position_1')
            if position_lat:
                latitude = position_lat
            else:
                latitude = 0
            if position_lon:
                longitude = position_lon
            else:
                longitude = 0
            # latitude = 0

            # return HttpResponse(businnes_type)
            # i = 1
            # for pos in position_get:
            #     if i == 1:
            #         latitude = Decimal(pos)
            #     if i == 2:
            #         longitude = Decimal(pos)
            #     i += 1
            doctors.position = Geoposition(latitude, longitude)
            doctors.save()
            return redirect(reverse('base:dashboard-education'))

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        doctor = Doctor.objects.get(user=self.request.user)

        context['ill'] = Xestelik.objects.all()
        context['country'] = Country.objects.all()
        context['doctor'] = doctor
        try:
            context['positionform'] = PositionForm(initial={
                'position': Geoposition(doctor.position.latitude, doctor.position.longitude)
            })
        except:
            context['positionform'] = PositionForm()
        return context


# # Check user online or not
# class AjaxRequestTestingView(View):
#
#     def post(self,request,*args,**kwargs):
#         if request.is_ajax():
#             data = request.POST
#             return JsonResponse({"online":"true"})
#
#     @method_decorator(csrf_exempt)
#     def dispatch(self, request, *args, **kwargs):
#         return super(AjaxRequestTestingView, self).dispatch(request, *args, **kwargs)

# Just a testing case
# class TestingView(View):
#     http_method_names = ['get', 'post']
#     template_name = 'development/base/index.html'
#
#     def get(self, request, *args, **kwargs):
#         print([m.upper() for m in self.http_method_names if hasattr(self, m)])
#         response = render(request, self.template_name, {})
#         response.cookies['munis'] = True
#         response._headers['Developer'] = ('Developer','Munis Isazade')
#         return render(request, self.template_name, {})


#####################################################################
################## Latest Footer Contact Form #######################
#####################################################################

class LeaveMessageView(TezsagalBaseView,
                       FormView):
    model = ContactMessages
    form_class = LeaveMessageForm


class Test(TezsagalBaseView, TemplateView):
    template_name = 'development/testing/index.html'


class PersonalInfoDoctorView(TezsagalBaseView,
                             FormView):
    template_name = 'production/base'


class DoctorFormsView(ListView):
    model = DoctorBlog
    queryset = DoctorBlog.objects.filter(status=True)
    template_name = 'production/forms/index.html'

    def get_nav_menu_contacts(self):
        obj = BaseContact.objects.all().last()
        return obj

    def get_context_data(self, **kwargs):
        context = super(DoctorFormsView, self).get_context_data(**kwargs)
        context['base_menu_contact'] = self.get_nav_menu_contacts()
        return context


class DoctorBlogDetailView(TezsagalBaseView,
                           DetailView):
    model = DoctorBlog
    template_name = 'production/blog/index.html'

    def get_context_data(self, **kwargs):
        context = super(DoctorBlogDetailView, self).get_context_data(**kwargs)
        return context


class DoctorTvView(TezsagalBaseView,
                   ListView):
    model = BlogTv
    template_name = 'production/tv/index.html'


class SendMail(View):
    def get(self, request, **kwargs):
        email_template = 'email/register.html'

doctor/templates/production/search/index.html
{% extends 'production/base/base_index.html' %}
{% load i18n %}
{% load static %}
{% load base_account %}
{% block aditional-css %}
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
    {% endblock %}
 {% block content %}



     <section class="two-column">
			<div class="container">
                {% comment %}<div class="sec-title text-center">
                    <h2><span>{% trans 'Axtarış' %}</span></h2>

                </div>{% endcomment %}
                <form action="{% url 'base:search' %}" method="get" enctype="multipart/form-data" id="searchForm">
                <div class="row">

                        <div class="col-md-5 col-5 col-xs-12">
                            <select class="js-example-basic-single search1 doct" name="ilness" multiple="multiple">
                                {% if illnes %}
                                    {% for data in illnes %}
                                        <option value="{{ data }}" selected hidden>{{ data|get_xestelik_name }}</option>
                                    {% endfor %}
                                {% endif %}
                                {% if ill %}
                                    {% for xestelik in ill %}
                                        <option value="{{ xestelik.id }}">{{ xestelik.name }}</option>
                                    {% endfor %}
                                {% endif %}
                            </select>
                        </div>
                        <div class="col-md-4 col-4 col-xs-12">
                            <select class="js-example-basic-single search2 doct" name="area" multiple="multiple">
                                {% if areas %}
                                    {% for data in areas %}
                                        <option value="{{ data }}" selected hidden>{{ data|get_country_name }}</option>
                                    {% endfor %}
                                {% endif %}
                                {% if country %}
                                    {% for city in country %}
                                        <option value="{{ city.id }}">{{ city.name }}</option>
                                    {% endfor %}
                                {% endif %}
                            </select>
                        </div>
                        <div class="col-md-3 col-3 col-xs-12">
                            <div class="link_btn float_left">
                                <a href="#" class="thm-btn enter-btn" onclick="$('#searchForm').submit()">
                                    <i class="fa fa-search" aria-hidden="true" ></i></a>
                            </div>
                        </div>

                </div>
                <br>
                <div class="row" style="background: #eee;padding: 17px 0px;">
                    <div class="col-md-2">
                        <p>{% trans 'Qiymət' %}</p>
                        <select name="money" class="form-control" id="">
                            <option value="" hidden>{% trans 'qiyməti seçin' %}</option>
                            {% if money %}
                                <option value="{{ money }}" selected hidden>{{ money }} manat</option>
                            {% endif %}
                            <option value="0-50">{% trans '0-50 manat' %}</option>

                            <option value="50-100">{% trans '50-100 manat' %}</option>

                            <option value="100-100000">{% trans '100+ manat' %}</option>
                        </select>
                    </div>
                    <div class="col-md-2">
                        <p>{% trans 'Cinsi' %}</p>
                        <select name="gender" class="form-control" id="">
                            <option value="" hidden>{% trans 'cinsi seçin' %}</option>
                            {% if gender %}
                                <option value="{{ gender }}" selected hidden>{% if gender == '1' %}Kişi{% elif gender == '0' %}{% trans 'Hər İkisi ' %}{% else %}Qadın{% endif %}</option>
                            {% endif %}
                            <option value="0">{% trans 'Hər İkisi ' %}</option>
                            <option value="1">{% trans 'Kişi' %}</option>

                            <option value="2">{% trans 'Qadın' %}</option>
                        </select>
                    </div>
                    <div class="col-md-2">
                        <p>Profil göstəricisi</p>
                        <select name="gosterici" class="form-control" id="">
                             <option value="" hidden>{% trans 'göstəricini seçin' %}</option>
                            {% if goster %}
                                <option value="{{ goster }}" selected hidden>{% trans 'göstəricini seçin' %}</option>
                            {% endif %}
                            <option value="1">{% trans '20 %' %}</option>
                            <option value="2">{% trans '40 %' %}</option>
                            <option value="3">{% trans '60 %' %}</option>
                            <option value="4">{% trans '80 %' %}</option>
                            <option value="5">{% trans '100 %' %}</option>
                        </select>
                    </div>
                    <div class="col-md-3">
                        <p>Reytinq</p>
                        <p style="color:#20bdb7; font-size: 30px;">&#9733;&#9733;&#9733;&#9733;&#9733;</p>
                    </div>
                    <br>
                    <div class="col-md-3">
                        <ul>
                            <li class="text-left"><input type="checkbox" style="float:left;"><span>{% trans 'Sertifikat' %}</span></li>
                            <li class="text-left"><input type="checkbox" style="float:left;"><span>{% trans 'Onlayn məsləhət' %}</span></li>
                            <li class="text-left"><input type="checkbox" style="float:left;"><span>{% trans 'Verified' %}</span></li>
                        </ul>
                    </div>
                </div>
                </form>
                <br>

                <div class="row banner">
                    {% if banner %}
                        {% for x in banner %}
                        <div class="col-sm-4 col-sm-4 col-xs-12 ban">
                        <p><img src="/media/{{ x.picture }}" alt=""></p>
                        </div>
                        {% endfor %}
                    {% else %}
                    <div class="col-sm-4 col-sm-4 col-xs-12 ban">
                        <p>{% trans 'Burada sizin reklam ola bilər' %}</p>
                    </div>
                   <div class="col-md-4 col-sm-4 col-xs-12 ban ban-mob">
                         <p>{% trans 'Burada sizin reklam ola bilər' %}</p>
                   </div>
                   <div class="col-md-4 col-sm-4 col-xs-12 ban ban-mob">
                         <p>{% trans 'Burada sizin reklam ola bilər' %}</p>
                   </div>
                    {% endif %}
                </div>
                <br>
                <br>
                {% if data %}
                {% for x in data %}
               <!-- doctor list -->
                <div class="row doctor_list doct_border doct-head">
                    <div class="col-md-4 col-sm-4 col-xs-12" style="margin: 13px 0px;"><b>{{ x.user.get_full_name }}<!-- <i class="fa fa-check-circle" style="font-size:24px; margin-left: 80px; color:darkslateblue;"></i> --></b></div>
                    <div class="col-md-4 col-sm-4 col-xs-6 position-doctor" style="margin: 0px 0px;"><b>{% for z in x.get_xestelik %}{{ z.xestelik.name }}{% if forloop.last %}{% else %},{% endif %}{% endfor %}</b></div>
                    <div class="col-md-2 col-sm-2 col-xs-12 position-money" style="text-align: right; color: #fff; margin-top: 15px"><span style="background: #ff2121;padding: 7px 13px;border-radius: 20px;" class="reqem">{{ x.qebul_qiymeti|default:"0" }} {{ x.prize_type|default:"azn" }}</span></div>
                    <div class="col-md-2 col-sm-2 col-xs-12" style="text-align: right; color: #fff; margin-top: 15px"></div>
                </div>
                <div class="row doct_border">
                    <div class="col-md-3 col-sm-3 col-xs-12 textalingcenter" style="text-align: center">
                        {% if x.user.profile_picture %}
                            <img style="max-width: 120px; height: auto; text-align: center; border-radius: 100%;" id="irc_ilrp_mut" src="/media/{{ x.user.profile_picture }}" height="250" width="250" style="margin-top: 69px;">
                        {% else %}
                        <img style="max-width: 120px; max-height: 120px; text-align: center;" id="irc_ilrp_mut" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb_kkdRW5lXoFVMDu3xHTCFsxLsyk9fNb60tIH5_65-q01zzRPjZeEkA" height="250" width="250" style="margin-top: 69px;">
                        {% endif %}
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                        <ul>
                            <li><p style="text-align: left;">{% trans 'Profil göstəricisi' %} {{ x.check_status }}%</p></li>
                            <li>
                                <div id="myProgress">
                                    <div id="myBar" style="width: {{ x.check_status }}%;background: #20bdb7">{{ x.check_status }}%</div>
                                </div>
                            </li>
                            <br>
                            <h5>{% trans 'Reytinq göstəricisi' %}</h5>
                            <fieldset class="rating">
                                <input type="radio" id="star5" name="rating" value="5" /><label class="full" for="star5" title="Awesome - 5 stars"></label>
                                <input type="radio" id="star4half" name="rating" value="4 and a half" /><label class="half" for="star4half" title="Pretty good - 4.5 stars"></label>
                                <input type="radio" id="star4" name="rating" value="4" /><label class="full" for="star4" title="Pretty good - 4 stars"></label>
                                <input type="radio" id="star3half" name="rating" value="3 and a half" /><label class="half" for="star3half" title="Meh - 3.5 stars"></label>
                                <input type="radio" id="star3" name="rating" value="3" /><label class="full" for="star3" title="Meh - 3 stars"></label>
                                <input type="radio" id="star2half" name="rating" value="2 and a half" /><label class="half" for="star2half" title="Kinda bad - 2.5 stars"></label>
                                <input type="radio" id="star2" name="rating" value="2" /><label class="full" for="star2" title="Kinda bad - 2 stars"></label>
                                <input type="radio" id="star1half" name="rating" value="1 and a half" /><label class="half" for="star1half" title="Meh - 1.5 stars"></label>
                                <input type="radio" id="star1" name="rating" value="1" /><label class="full" for="star1" title="Sucks big time - 1 star"></label>
                                <input type="radio" id="starhalf" name="rating" value="half" /><label class="half" for="starhalf" title="Sucks big time - 0.5 stars"></label>
                            </fieldset>
                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                        <ul>
                            <li><i class="glyphicon glyphicon-map-marker" style="color:darkslateblue;"><span style="color: black;"> Məkan</span></i></li>
                            <li><span>{{ x.base_name|default:"" }}</span></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                        <ul>
                            <li><i class="fa fa-star" style="font-size:24px; color: #FFD700"></i><span> {% trans 'Özəllik' %}</span></li>
                            <li><i class="fa fa-dot-circle-o" aria-hidden="true"><span> {% trans 'Online məsləhət' %}</span></i></li>
                        </ul>
                    </div>

                </div>
                <!-- gorus iste profilini  gor -->
                <div class="row apply">
                    <div class="col-md-10 col-sm-10 col-xs-6">
                        <button class="appoinment" {% if not request.user.is_authenticated %} onclick="alert('{% trans 'Görüş üçün saytda qeydiyyatdan keçin' %}')" {% else %}onclick="location.href='{% url 'base:doctor-meet' %}?doctor={{ x.id }}&user={{ request.user.id }}'"{% endif %}><i class="fa fa-calendar" style="font-size:18px;"><span style="margin-left: 8px;">{% trans 'GÖRÜŞ İSTƏ' %}</span></i></button>
                    </div>
                    <div class="col-md-2 col-sm-2 col-xs-6">
                        <button class="profile_gor" onclick="location.href='{% url 'base:doctor-detail' slug=x.user.slug %}'"><i class="fa fa-file-text-o" style="font-size:18px; color: white;"><span style="margin-left: 8px; color: white;">{% trans 'PROFİLİNİ GÖR' %}</span></i></button>
                    </div>
                </div>
                <br>
                <br>
                {% endfor %}
                {% else %}
                    <p class="text-center">{% trans 'Axtarışınıza uyğun həkim tapılmadı' %}</p>
                {% endif %}
                <br>
                <br>
                <br>

			</div>
		</section>




{% endblock %}